<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NetLights.Core</RootNamespace>
    <AssemblyName>NetLights.Core</AssemblyName>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NetLights.UnitTests" />
    <InternalsVisibleTo Include="NetLights.IntegrationTests" />
    <InternalsVisibleTo Include="NetLights.SoakTests" />
  </ItemGroup>
</Project>
