<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NetLights.Networking</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetLights.Core\NetLights.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NetLights.UnitTests" />
    <InternalsVisibleTo Include="NetLights.IntegrationTests" />
  </ItemGroup>
</Project>
