<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>NetLights.App</RootNamespace>
    <AssemblyName>NetLights</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetLights.Core\NetLights.Core.csproj" />
    <ProjectReference Include="..\NetLights.Networking\NetLights.Networking.csproj" />
  </ItemGroup>
    <ItemGroup>
      <InternalsVisibleTo Include="NetLights.IntegrationTests" />
      <InternalsVisibleTo Include="NetLights.UnitTests" />
    </ItemGroup>
  </Project>
